KTConstructionWebApp/KTConstruction/Controllers/ContactController.cs
using KTConstruction.Model.Data;
using KTConstruction.Model.Interfaces;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTConstruction.Controllers
{
    public class ContactController : Controller
    {
        private IMailModel _mailModel;

        public ContactController()
        {
            this._mailModel = new MailModel();
        }

        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost, ValidateInput(true)]
        public ActionResult SendMail()
        {
            NameValueCollection nvc = Request.Form;
            string emailFrom = nvc["emailFrom"];
            string emailContent = nvc["emailContent"];
            bool status = this._mailModel.SendMail(emailFrom, emailContent);
            return Json(new
            {
                status = status
            }, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("Index", "Contact");
        }
    }
}

KTConstructionWebApp/KTConstruction/Controllers/HomeController.cs
using KTConstruction.Model.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KTConstruction.Model.Interfaces;

namespace KTConstruction.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            //ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

KTConstructionWebApp/KTConstruction/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTConstruction.Controllers
{
    public class ServicesController : Controller
    {
        // GET: Services
        public ActionResult Index()
        {
            return View();
        }
    }
}

KTConstructionWebApp/KTConstruction/Controllers/TestimonialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KTConstruction.Controllers
{
    public class TestimonialsController : Controller
    {
        // GET: Testimonials
        public ActionResult Index()
        {
            return View();
        }
    }
}

KTConstructionWebApp/KTConstruction/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Контакти";
}

@section links {
    <script type="text/javascript" src="~/Scripts/Contacts/Service.js"></script>
    <script type="text/javascript" src="~/Scripts/Contacts/ViewModel.js"></script>
    <script type="text/javascript" src="~/Scripts/Contacts/Controller.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            Controller.init();
        };
    </script>
}


<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    <div class="row">
        <div class="col-md-6">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5865.523778003851!2d23.329734491054175!3d42.68758591709194!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40aa850abb15ba19%3A0x7977ca9c656e94d7!2sBulevard+%22Evlogi+i+Hristo+Georgiev%22+97%2C+1142+Sofia+Center%2C+Sofia!5e0!3m2!1sen!2sbg!4v1506267233418" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <div class="col-md-6 form-group">
            <label for="emailFrom">От: </label>
            <input type="email" class="form-control" name="emailFrom" />
            <label for="comment">Коментар:</label>
            <textarea class="form-control" rows="10" id="comment" name="emailContent"></textarea>
            <input type="button" onclick="sendMail(this, 'emailFrom', 'emailContent');" class="btn btn-default sendEmail" value="Изпрати" />
        </div>
    </div>
</address>

<address>
    <span>Bulevard "Evlogi i Hristo Georgiev" 97</span><br />
    <span>1142 Sofia Center, Sofia</span><br />
    <abbr title="Phone">Ph:</abbr><span>+35988*******</span>
</address>

<address>
    <strong>Support:</strong>
    <a href="mailto:Support@example.com">Support@example.com</a>
</address>

KTConstructionWebApp/KTConstruction/Views/Home/About.cshtml
@{
    ViewBag.Title = "За нас";
}

@section links {
    <style type="text/css">
        #mainBody {
            padding: 30px 0px;
            margin-top: 30px;
            width: 100%;
            background-color: #efefef;
            font-size: 1.3em;
        }

            #mainBody * {
                font-style: italic;
            }

            #mainBody .row {
                padding: 0px 30px;
            }

            #mainBody h3,
            #mainBody i {
                color: #e05858;
            }

            #mainBody i {
                line-height: 3;
            }

        ul {
            list-style-type: none;
        }
    </style>

    <script type="text/javascript" src="~/Scripts/AboutUs/Service.js"></script>
    <script type="text/javascript" src="~/Scripts/AboutUs/ViewModel.js"></script>
    <script type="text/javascript" src="~/Scripts/AboutUs/Controller.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            Controller.init();
        };
    </script>
}

<div id="mainBody" class="container">
    <div class="row">
        <h3>Кои сме ние?</h3>
        <p>KT Кънстракшън вярва, че строителството е най-важният инструмент за постигане на желаният уют и комфорт във вашият дом.</p>
    </div>
    <div class="row">
        <h3>Нашите принципи</h3>
        <p>Създадена през 2010 година, в основите на фирмата са заложени:</p>
        <ul>
            <li><i class="glyphicon glyphicon-check"></i> Съдействие на клиентите в реализацията на техните идеи, впечатления и проекти</li>
            <li><i class="glyphicon glyphicon-indent-right"></i> Качествени услуги на разумни цени</li>
            <li><i class="glyphicon glyphicon-thumbs-up"></i> Лоялно отношение към всеки наш клиент и партньор</li>
            <li><i class="glyphicon glyphicon-hand-right"></i> K Кънстракшън вярва, че строителството е най-важният инструмент за постигане на желаният уют и комфорт във вашият дом</li>
        </ul>
    </div>
</div>

<div id="sightseeing" class="row">
    <div class="be-section-pad clearfix " style="padding-top:60px;padding-bottom:60px;" data-padding-top="60">
        <div class="be-row">
            <div class="col-md-2 gal-item">
                <div class="be-custom-column-inner">
                    <div class="animate-number-wrap align-center">
                        <span id="allProjects" style="color:#323232;font-size:45px;line-height:1.3"></span>
                        <h6>
                            <span class="animate-number-caption" style="color:#323232;font-size:13px;">Oбщо проекти</span>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="col-md-2 gal-item">
                <div class="be-custom-column-inner">
                    <div class="animate-number-wrap align-center">
                        <span id="interiorRepairs" style="color:#323232;font-size:45px;line-height:1.3"></span>
                        <h6>
                            <span class="animate-number-caption" style="color:#323232;font-size:13px;">Интериорни</span>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="col-md-2 gal-item">
                <div class="be-custom-column-inner">
                    <div class="animate-number-wrap align-center">
                        <span id="exteriorRepairs" style="color:#323232;font-size:45px;line-height:1.3"></span>
                        <h6>
                            <span class="animate-number-caption" style="color:#323232;font-size:13px;">Екстериорни</span>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="col-md-2 gal-item">
                <div class="be-custom-column-inner">
                    <div class="animate-number-wrap align-center">
                        <span id="bathRepairs" style="color:#323232;font-size:45px;line-height:1.3"></span>
                        <h6>
                            <span class="animate-number-caption" style="color:#323232;font-size:13px;">Ремонт на баня</span>
                        </h6>
                    </div>
                </div>
            </div>
            <div class="col-md-2 gal-item">
                <div class="be-custom-column-inner">
                    <div class="animate-number-wrap align-center">
                        <span id="currentProjects" style="color:#323232;font-size:45px;line-height:1.3"></span>
                        <h6>
                            <span class="animate-number-caption" style="color:#323232;font-size:13px;">Текущи проекти</span>
                        </h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

KTConstructionWebApp/KTConstruction/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакти";
}

@section links {
    <script type="text/javascript" src="~/Scripts/Contacts/Service.js"></script>
    <script type="text/javascript" src="~/Scripts/Contacts/ViewModel.js"></script>
    <script type="text/javascript" src="~/Scripts/Contacts/Controller.js"></script>
    <script type="text/javascript">
        window.onload = function () {
            Controller.init();
        };
    </script>
}


<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    <div class="row">
        <div class="col-md-6">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5865.523778003851!2d23.329734491054175!3d42.68758591709194!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40aa850abb15ba19%3A0x7977ca9c656e94d7!2sBulevard+%22Evlogi+i+Hristo+Georgiev%22+97%2C+1142+Sofia+Center%2C+Sofia!5e0!3m2!1sen!2sbg!4v1506267233418" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <div class="col-md-6 form-group">
            <form action="#" method="post">
                <label for="emailFrom">От: </label>
                <input type="text" class="form-control" name="emailFrom" />
                <label for="comment">Коментар:</label>
                <textarea class="form-control" rows="10" id="comment"></textarea>
                <input type="submit" class="btn btn-primary" value="Изпрати" />
            </form>
        </div>
    </div>
</address>

<address>
    <span>Bulevard "Evlogi i Hristo Georgiev" 97</span><br />
    <span>1142 Sofia Center, Sofia</span><br />
    <abbr title="Phone">Ph:</abbr><span>+35988*******</span>
</address>

<address>
    <strong>Support:</strong>
    <a href="mailto:Support@example.com">Support@example.com</a>
</address>

KTConstructionWebApp/KTConstruction/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Начало";
}

@section links {
    <style type="text/css">
        #myCarousel .pull-left {
            padding: 30px;
            background: rgba(51, 51, 51, 0.7);
        }

        /*#myCarousel img {
            max-height: initial;
            clip: rect(0px, 60px, 200px, 0px);
        }*/

        .header-image-holder {
            width: 100%;
            height: 400px;
            overflow: hidden;
            position: relative;
        }

        #myCarousel img {
            position: absolute;
            width: 100%;
        }

        #homeContent {
            margin-top: 20px;
            margin-bottom: 20px;
            padding-top: 50px;
            padding-bottom: 20px;
            width: 100%;
            background-color: #efefef;
        }
            #homeContent p,
            #homeContent a {
                font-style: italic;
            }

            #homeContent .row {
                padding: 15px;
            }

            #homeContent .one-thing {
                font-size: 1.2em;
            }

                #homeContent .one-thing i {
                    font-size: 5em;
                    color: #e05858;
                }

                #homeContent .one-thing a {
                    color: #e05858;
                }
        div.col-xs-7 div.row {
            background-color: initial;
            -webkit-transition: background-color 1000ms linear;
            -moz-transition: background-color 1000ms linear;
            -o-transition: background-color 1000ms linear;
            -ms-transition: background-color 1000ms linear;
            transition: background-color 1000ms linear;
        }

            div.col-xs-7 div.row:hover {
                background-color: #e1e1e1;
            }

                div.col-xs-7 div.row:hover a,
                div.col-xs-7 div.row:hover i {
                    color: #ca2d2d !important;
                }

    </style>
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="header-image-holder">
                <img src="~/Images/Construction/Екстериорни ремонти/IMG_20170724_150436.jpg" style="top:0px;" alt="Image">
            </div>
            <div class="carousel-caption">
                <div class="pull-left">
                    <h3>Екстериорни Ремонти</h3>
                    <a class="btn btn-block btn-default" href="/Testimonials#?exteriorRepair" target="_self">Вижте още</a>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="header-image-holder">
                <img src="~/Images/Construction/Интериорни ремонти/IMG_20170707_151039.jpg" style="top:-300px;" alt="Image">
            </div>
            <div class="carousel-caption">
                <div class="pull-left">
                    <h3>Интериорни Ремонти</h3>
                    <a class="btn btn-block btn-default" href="/Testimonials#?interiorRepair" target="_self">Вижте още</a>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="header-image-holder">
                <img src="~/Images/Construction/Ремонт на Баня/IMG_20170707_150939.jpg" style="top:-300px;" alt="Image">
            </div>
            <div class="carousel-caption">
                <div class="pull-left">
                    <h3>Ремонти на Баня</h3>
                    <a class="btn btn-block btn-default" href="/Testimonials#?bathRepair" target="_self">Вижте още</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<section>
    <div id="homeContent" class="container">
        <h3>Четири неща, които трябва да знаете за това кои сме ние и как предпочитаме да работим:</h3>
        <div class="row">
            <div class="col-xs-7">
                <p></p>
                <div class="row">
                    <div class="one-thing">
                        <div class="col-md-2">
                            <i class="glyphicon glyphicon-refresh"></i>
                        </div>
                        <div class="col-md-10">
                            <a href="/Home/About">Екип</a><br>
                            <p>За да бъдем сигурни,че основната цел е винаги доведена до успешен край, тези принципи са неразделна част от нашият екип, съставен от специалисти с необходимата квалификация и рутина.</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="one-thing">
                        <div class="col-md-2">
                            <i class="glyphicon glyphicon-th-list"></i>
                        </div>
                        <div class="col-md-10">
                            <a href="/Testimonials">Портфолио</a><br>
                            <p>Портфолиото ни е комбинация от решения с най-новите иновации и технологии в полза на нашите клиенти. Вижте нашата галерия</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="one-thing">
                        <div class="col-md-2">
                            <i class="glyphicon glyphicon-usd"></i>
                        </div>
                        <div class="col-md-10">
                            <a href="/Testimonials">На каква цена?</a><br>
                            <p>В основата нашите ценови модел са елементите:</p>
                            <p><strong>добро планиране > успешен ремонт > щастлив клиент</strong></p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="one-thing">
                        <div class="col-md-2">
                            <i class="glyphicon glyphicon-pushpin"></i>
                        </div>
                        <div class="col-md-10">
                            <a href="/Testimonials">Послание</a><br>
                            <p>Ние даваме възможност на вашите най-смели идеи и очаквания да се превърнат в реалност.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
            </div>
        </div>
    </div>
</section>

KTConstructionWebApp/KTConstruction/Views/Services/Index.cshtml
@{
    ViewBag.Title = "Услуги";
}

@section links {
    <style type="text/css">
        #main .container-fluid:not(.aside-navigation) {
            margin-top: 30px;
            margin-bottom: 30px;
            width: 100%;
        }
            #main .container-fluid a {
                width: 100%;
            }
            
            #main .container-fluid p {
                padding: 10px;
                color: white;
            }
 
            #main .container-fluid i {
                font-size: 6em;
            }

            #main .container-fluid ul i {
                font-size: 1em;
            }

        #main ul {
            list-style-type: none;
        }

            #main ul li {
                text-align: left;
                font-size: 1.4em;
            }

            #main ul.secondary {
                font-size: 0.8em;
            }

        /* hide elements */
        .col-md-4 ul:not(.secondary) li {
            opacity: 0;
            transition: opacity .5s ease-in-out;
            -moz-transition: opacity .5s ease-in-out;
            -webkit-transition: opacity .5s ease-in-out;
        }
    </style>
    <script type="text/javascript">
        window.onload = function () {
            loadServices();
        };
        function modifyElement(elem, time) {
            setTimeout(function () {
                if (elem.style) {
                    elem.style.opacity = "1";
                }
            }, 200 * time);
        }
        function loadServices(elemId) {
            var ulElements = document.querySelectorAll('.col-md-4 ul:not(.secondary)' + (elemId ? '#' + elemId : ''));
            if (elemId) {
                ulElements.forEach(function (el) {
                    liInUl = el.getElementsByTagName('li');
                    for (var ind in liInUl) {
                        elem = liInUl[ind];
                        if (typeof elem != "function" && elem.style) {
                            elem.style.opacity = "0";
                        }
                    }
                });
            }
            ulElements.forEach(function (el) {
                liInUl = el.getElementsByTagName('li');
                for (var ind in liInUl) {
                    elem = liInUl[ind];
                    if (typeof elem != "function") {
                        modifyElement(elem, parseInt(ind));
                    }
                }
            });
        }
    </script>
}

<div class="container-fluid bg-3 text-center">
    <div class="row">
        <div class="col-md-4">
            <h3>Ремонт на Интериор</h3>
            <a class="btn btn-danger" href="/Testimonials#?interiorRepair" onmouseenter="loadServices('interior');">
                <p><i class="glyphicon glyphicon-modal-window"></i></p>
                <!--    
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
                -->
            </a>
            <ul id="interior" style="margin-top: 30px;">
                <li><i class="glyphicon glyphicon-ok-circle"></i> Обзавеждане</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> Дизайн и Реновации</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> 
                    Високо качествени покрития:
                    <ul class="secondary">
                        <li><i class="glyphicon glyphicon-circle-arrow-right"></i> Боядисване</li>
                        <li><i class="glyphicon glyphicon-circle-arrow-right"></i> Мазилки</li>
                        <li><i class="glyphicon glyphicon-circle-arrow-right"></i> Шпакловки</li>
                        <li><i class="glyphicon glyphicon-circle-arrow-right"></i> Замазки</li>
                    </ul>
                </li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> 
                    Настилки:
                    <ul class="secondary">
                        <li><i class="glyphicon glyphicon-circle-arrow-right"></i> Паркети</li>
                        <li><i class="glyphicon glyphicon-circle-arrow-right"></i> Ламперии</li>
                        <li><i class="glyphicon glyphicon-circle-arrow-right"></i> Плочки</li>
                    </ul>
                </li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> ВиК услуги</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> Ел. Услуги</li>
            </ul>
        </div>
        <div class="col-md-4">
            <h3>Ремонт на баня</h3>
            <a class="btn btn-danger" href="/Testimonials#?bathRepair" onmouseenter="loadServices('bath');">
                <p><i class="glyphicon glyphicon-wrench"></i></p>
                <!--
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
                -->
            </a>
            <ul id="bath" style="margin-top: 30px;">
                <li><i class="glyphicon glyphicon-ok-circle"></i> Дизайн</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> Предекориране</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> Обзавеждане</li>
            </ul>
        </div>
        <div class="col-md-4">
            <h3>Екстериорен ремонт</h3>
            <a class="btn btn-danger" href="/Testimonials#?exteriorRepair" onmouseenter="loadServices('exterior');">
                <p><i class="glyphicon glyphicon-home"></i></p>
                <!--
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
                -->
            </a>
            <ul id="exterior" style="margin-top: 30px;">
                <li><i class="glyphicon glyphicon-ok-circle"></i> Дограми</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> Зидарии</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> Ремонт на покриви</li>
                <li><i class="glyphicon glyphicon-ok-circle"></i> Изолации</li>
            </ul>
        </div>
    </div>
</div>

KTConstructionWebApp/KTConstruction/Views/Shared/_AsideMail.cshtml
<div class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid aside-navigation">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <div class="btn-group dropup">
                    <button type="button" class="btn btn-danger dropdown-toggle" id="sendMessageDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope-open" style="font-size:36px;"></i>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="sendMessageDropdown" style="min-width: 220px; padding: 10px; background-color: white; border: 1px solid black;">
                        <label for="asideMailFrom">От: </label>
                        <input type="email" name="asideMailFrom" />
                        <label for="asideMailContent">Коментар: </label>
                        <textarea style="width: 100%; height: 200px; resize: none;" name="asideMailContent"></textarea>
                        <button id="sendAsideEmail" class="btn btn-default dropdown-item sendEmail" type="button" style="width: 100%;">Изпрати</button>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

KTConstructionWebApp/KTConstruction/Views/Shared/_Footer.cshtml
<footer class="footer">
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="glyphicon glyphicon-home"></i>
                <span>бул. „Евлоги и Христо Георгиеви“ 97</span><br />
                <span>1142 Център, София</span>
            </div>
            <div class="col-md-4">
                <a href="https://goo.gl/maps/dFg146KCVqu" target="_blank" class="btn btn-danger"><i class="glyphicon glyphicon-map-marker"></i> Преглед на адреса в Google Maps</a>
            </div>
            <div class="col-md-4">
                <i class="glyphicon glyphicon-earphone"></i> +3598********
            </div>
        </div>
    </div>
    <p id="footerCopyright">&copy; @DateTime.Now.Year - К Констръкшън</p>
</footer>

KTConstructionWebApp/KTConstruction/Views/Shared/_ModalView.cshtml
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

KTConstructionWebApp/KTConstruction/Views/Shared/_Navigation.cshtml
<div class="navbar navbar-fixed-top">
    <div id="mainNavigationBar" class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="~/Images/logo.gif" alt="logo" />
            </a>
        </div>
        <div class="navbar-collapse collapse pull-right">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Начало", "Index", "Home")</li>
                <li>@Html.ActionLink("Услуги", "Index", "Services")</li>
                <li>@Html.ActionLink("Галерия", "Index", "Testimonials")</li>
                <li>@Html.ActionLink("За нас", "About", "Home")</li>
                <li>@Html.ActionLink("Контакти", "Index", "Contact")</li>
            </ul>
        </div>
    </div>
</div>